sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - redis-server
install:
  - pip install --upgrade pytest pytest-cov pytest-flake8
script:
  - python setup.py test --addopts='-vv --cov --flake8'
